In [1]:
import pandas as pd
import numpy  as np
from IPython.display import display

In [2]:
# Exercise
# Use Churn_Modelling.csv
# Create a notebook, solve any 3 questions from Task 1 to Task 10, and solve Task 11

In [3]:
# Task 1
# Setup & data: Load the file with df = pd.read_csv('Churn_Modelling.csv').
# Display the first 7 rows, then print df.shape and df.columns
df = pd.read_csv('Churn_Modelling.csv')
display(df.head(7))
print(f'\n df.shape -> {df.shape}\n')
print(f'df.columns -> {df.columns}')

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
5,6,15574012,Chu,645,Spain,Male,44,8,113755.78,2,1,0,149756.71,1
6,7,15592531,Bartlett,822,France,Male,50,7,0.00,2,1,1,10062.80,0

 df.shape -> (10000, 14)

df.columns -> Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

In [4]:
# Task 2
# Sorting: Sort customers by CreditScore from lowest to highest and show the first 7 rows
df = pd.read_csv('Churn_Modelling.csv')
display(df.sort_values(by=['CreditScore'], ascending=True).head(7))

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
8762,8763,15765173,Lin,350,France,Female,60,3,0.00,1,0,0,113796.15,1
8723,8724,15803202,Onyekachi,350,France,Male,51,10,0.00,1,1,1,125823.79,1
1838,1839,15758813,Campbell,350,Germany,Male,39,0,109733.20,2,0,0,123602.11,1
9624,9625,15668309,Maslow,350,France,Female,40,0,111098.85,1,1,1,172321.21,1
1631,1632,15685372,Azubuike,350,Spain,Male,54,1,152677.48,1,1,1,191973.49,1
2473,2474,15679249,Chou,351,Germany,Female,57,4,163146.46,1,1,0,169621.69,1
1962,1963,15692416,Aikenhead,358,Spain,Female,52,8,143542.36,3,1,0,141959.11,1

In [5]:
# Task 3
# Multi-column sorting: Sort by Geography ascending and Balance descending.
# Show the first 12 rows and explain what the two sort directions mean
df = pd.read_csv('Churn_Modelling.csv')
display(df.sort_values(by=['Geography', 'Balance'], ascending=[True, False]).head(12))
# Geography ascending -> lowest to highest this means sorting alphabetically (A to Z).
# Balance descending -> highest to lowest this means sorting numerically decreasing.

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
3280,3281,15715622,To Rot,583,France,Female,57,3,238387.56,1,0,1,147964.99,1
1533,1534,15769818,Moore,850,France,Female,37,3,212778.20,1,0,1,69372.88,0
2709,2710,15780212,Mao,592,France,Male,37,4,212692.97,1,0,0,176395.02,0
8702,8703,15690589,Udinesi,541,France,Male,37,9,212314.03,1,0,1,148814.54,0
520,521,15671256,Macartney,850,France,Female,35,1,211774.31,1,1,0,188574.12,1
7353,7354,15736420,Macdonald,596,France,Male,21,4,210433.08,2,0,1,197297.77,1
5871,5872,15709920,Burke,479,France,Female,33,2,208165.53,1,0,0,50774.81,1
8982,8983,15627971,Coates,504,France,Female,32,8,206663.75,1,0,0,16281.94,0
6913,6914,15784180,Ku,564,France,Female,36,7,206329.65,1,1,1,46632.87,1
4436,4437,15664498,Golovanov,508,France,Male,26,7,205962.00,1,1,0,156424.40,0
9920,9921,15673020,Smith,678,France,Female,49,3,204510.94,1,0,1,738.88,1
6271,6272,15620756,Stokes,747,France,Male,49,6,202904.64,1,1,1,17298.72,1

In [6]:
# Task 4
# Counts: Use value_counts() to count customers by Geography.
# Then count each Geography + Gender combination
df = pd.read_csv('Churn_Modelling.csv')
display(df['Geography'].value_counts())
print()
display(df[['Geography', 'Gender']].value_counts())

Geography
France     5014
Germany    2509
Spain      2477
Name: count, dtype: int64

Geography  Gender
France     Male      2753
           Female    2261
Spain      Male      1388
Germany    Male      1316
           Female    1193
Spain      Female    1089
Name: count, dtype: int64

In [7]:
# Task 5
# Unique values: Show the unique values in Geography, Gender, NumOfProducts, and Exited.
# Then use nunique() to count how many different values each of these columns has
df = pd.read_csv('Churn_Modelling.csv')
columns = ['Geography', 'Gender', 'NumOfProducts', 'Exited']

for col in columns:
    display(f'{col} unique values: {df[col].unique()}')
print()
for col in columns:
    display(f'{col} nunique values: {df[col].nunique()}')

"Geography unique values: ['France' 'Spain' 'Germany']"

"Gender unique values: ['Female' 'Male']"

'NumOfProducts unique values: [1 3 2 4]'

'Exited unique values: [1 0]'

'Geography nunique values: 3'

'Gender nunique values: 2'

'NumOfProducts nunique values: 4'

'Exited nunique values: 2'

In [8]:
# Task 6
# Replace & map: Create a copy of the DataFrame.
# In the copy, replace Female with F and Male with M using .replace().
# Then solve the same change with .map()
df_copy_replace = df.copy()
df_copy_replace['Gender'] = df_copy_replace['Gender'].replace(['Female', 'Male'], ['F', 'M'])
display(df_copy_replace['Gender'].to_frame())
print()
df_copy_map = df.copy()
df_copy_map['Gender'] = df_copy_map['Gender'].map({'Female': 'F', 'Male': 'M'})
display(df_copy_map['Gender'].to_frame())

     Gender
0         F
1         F
2         F
3         F
4         F
...     ...
9995      M
9996      M
9997      F
9998      M
9999      F

[10000 rows x 1 columns]

     Gender
0         F
1         F
2         F
3         F
4         F
...     ...
9995      M
9996      M
9997      F
9998      M
9999      F

[10000 rows x 1 columns]

In [9]:
# Task 7
# Top & lowest values: Find the 6 customers with the highest Balance using nlargest.
# Then find the 4 customers with the lowest CreditScore using nsmallest
df = pd.read_csv('Churn_Modelling.csv') # shows the sex highest Balace.
display(df.nlargest(6, 'Balance'))
print()
display(df.nsmallest(4, 'CreditScore')) # shows the four lowest CreditScore.

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
2092,2093,15757408,Lo,655,Spain,Male,38,3,250898.09,3,0,1,81054.00,1
3280,3281,15715622,To Rot,583,France,Female,57,3,238387.56,1,0,1,147964.99,1
8733,8734,15714241,Haddon,749,Spain,Male,42,9,222267.63,1,0,0,101108.85,1
3588,3589,15571958,McIntosh,489,Spain,Male,40,3,221532.80,1,1,0,171867.08,0
6717,6718,15586674,Shaw,663,Spain,Female,58,5,216109.88,1,0,1,74176.71,1
1067,1068,15599131,Dilke,650,Germany,Male,26,4,214346.96,2,1,0,128815.33,0

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
1631,1632,15685372,Azubuike,350,Spain,Male,54,1,152677.48,1,1,1,191973.49,1
1838,1839,15758813,Campbell,350,Germany,Male,39,0,109733.20,2,0,0,123602.11,1
8723,8724,15803202,Onyekachi,350,France,Male,51,10,0.00,1,1,1,125823.79,1
8762,8763,15765173,Lin,350,France,Female,60,3,0.00,1,0,0,113796.15,1

In [10]:
# Task 8
# sample(): Show 9 random customers using sample(9).
# Then show a 3% random sample using sample(frac=0.03)
df = pd.read_csv('Churn_Modelling.csv')
display(df.sample(9))
print()
display(df.sample(frac=0.03))

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
4855,4856,15671148,Barry,490,Germany,Male,33,5,96341.00,2,0,0,108313.34,0
234,235,15704769,Smith,585,France,Female,67,5,113978.97,2,0,1,93146.11,0
5320,5321,15591550,Bianchi,525,Spain,Male,36,3,77910.23,1,1,0,67238.01,0
311,312,15702919,Collins,729,Germany,Male,30,6,63669.42,1,1,0,145111.37,0
2556,2557,15567486,Li,634,Spain,Female,41,4,0.00,2,1,1,164549.74,0
3340,3341,15809263,Y?,729,Germany,Male,29,5,109676.52,1,1,1,25548.47,0
4454,4455,15641312,Paterson,615,France,Male,36,6,0.00,1,1,1,27011.80,1
8981,8982,15685805,Ginikanwa,673,Spain,Female,35,6,0.00,2,1,0,98618.79,0
5682,5683,15759290,Coleman,620,Spain,Male,29,9,0.00,2,1,0,13133.88,0

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
2319,2320,15681446,Sun,636,Germany,Female,37,9,157098.52,1,1,1,153535.27,0
302,303,15695699,Calabrese,687,France,Male,35,8,0.00,2,1,0,10334.05,0
2898,2899,15624510,Tien,696,France,Male,52,6,139781.06,1,1,0,27445.40,1
4471,4472,15642824,Onyekaozulu,826,Spain,Female,56,8,174506.10,2,0,1,161802.82,1
6551,6552,15651740,Napolitani,525,Spain,Female,30,5,0.00,2,0,1,149195.44,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9919,9920,15798084,Murray,688,France,Male,26,0,0.00,2,1,0,105784.85,0
7932,7933,15812365,Greco,850,France,Male,40,8,102800.65,1,1,0,60811.56,0
7957,7958,15582149,Ts'ui,850,Germany,Female,34,3,129668.43,2,1,1,88743.99,0
8194,8195,15620746,Lorenzo,632,France,Male,42,4,126115.60,1,1,0,100998.50,0
1556,1557,15772777,Onyemachukwu,850,Spain,Female,29,10,0.00,2,1,1,94815.04,0

In [11]:
# Task 9
# Duplicates: Check whether the dataset has duplicated CustomerId values.
# Then use sorting plus drop_duplicates('Geography') to keep one customer per country with the highest Balance

df = pd.read_csv('Churn_Modelling.csv')
print(f'Are there duplicated CustomerIds? {df['CustomerId'].duplicated().any()}')
display(df['CustomerId'].duplicated().to_frame())
display(df.sort_values(by= ['Balance'], ascending=[False]).drop_duplicates(subset=['Geography'], keep='first'))

Are there duplicated CustomerIds? False

      CustomerId
0          False
1          False
2          False
3          False
4          False
...          ...
9995       False
9996       False
9997       False
9998       False
9999       False

[10000 rows x 1 columns]

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
2092,2093,15757408,Lo,655,Spain,Male,38,3,250898.09,3,0,1,81054.00,1
3280,3281,15715622,To Rot,583,France,Female,57,3,238387.56,1,0,1,147964.99,1
1067,1068,15599131,Dilke,650,Germany,Male,26,4,214346.96,2,1,0,128815.33,0

In [12]:
# Task 10
# Largest values plus unique values: Find the 12 customers with the highest EstimatedSalary.
# From those rows, print the unique Geography values

df = pd.read_csv('Churn_Modelling.csv')
display(df.nlargest(12, 'EstimatedSalary'))
print()
display(df.nlargest(12, 'EstimatedSalary')['Geography'].unique())

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
6646,6647,15662021,Lucciano,685,Spain,Female,42,2,0.00,2,0,0,199992.48,0
3580,3581,15634359,Dyer,639,Germany,Female,41,5,98635.77,1,1,0,199970.74,0
4417,4418,15697270,Gannon,608,Spain,Male,27,4,153325.10,1,1,1,199953.33,0
9096,9097,15762331,Moss,569,France,Male,37,9,178755.84,1,1,0,199929.17,0
8926,8927,15709136,Adams,620,France,Male,28,8,0.00,2,1,1,199909.32,0
5958,5959,15741719,DeRose,540,France,Female,40,3,165298.12,1,0,1,199862.75,0
1378,1379,15682834,Johnstone,715,Spain,Female,35,4,40169.88,2,1,1,199857.47,0
6402,6403,15804211,Oluchukwu,719,France,Male,36,3,155423.17,1,1,1,199841.32,0
8088,8089,15815656,Hopkins,541,Germany,Female,39,9,100116.67,1,1,1,199808.10,1
6125,6126,15687913,Mai,501,Germany,Female,34,7,93244.42,1,0,1,199805.63,0
3830,3831,15720713,Chibueze,850,France,Female,29,10,0.00,2,1,1,199775.67,0
1986,1987,15772601,Lu,845,Germany,Female,41,2,81733.74,2,0,0,199761.29,0

array(['Spain', 'Germany', 'France'], dtype=object)

In [13]:
# Task 11
# Missing data: Use the DataFrame below and implement the requested cleaning operations

df_missing = pd.DataFrame({
    'A': [None, 2, 3, None, 5, None],
    'B': [10, None, None, 40, 50, None],
    'C': [100, None, 300, 400, None, None]
})
display(df_missing)
print('Task 11 -> Q1')
# Eliminate any row in the DataFrame that contains at least one NaN value
display(df_missing.dropna())
print('\nTask 11 -> Q2')
# Modify the previous task and eliminate only rows that have NaN values across all columns
display(df_missing.dropna(thresh=1))
print('\nTask 11 -> Q3')
# Eliminate rows that have at least one NaN in columns A and C only
display(df_missing.dropna(subset=['A', 'C']))
print('\nTask 11 -> Q4')
# Replace all NaN values with a specified value of your choice
df_filled = df_missing.fillna(1)
display(df_filled)
print('\nTask 11 -> Q5')
# Replace all NaN values in column B with the mean of the non-NaN values in that column
df_missing['B'] = df_missing['B'].fillna(df_missing['B'].mean())
display(df_missing)

     A     B      C
0  NaN  10.0  100.0
1  2.0   NaN    NaN
2  3.0   NaN  300.0
3  NaN  40.0  400.0
4  5.0  50.0    NaN
5  NaN   NaN    NaN

Task 11 -> Q1

Empty DataFrame
Columns: [A, B, C]
Index: []

Task 11 -> Q2

     A     B      C
0  NaN  10.0  100.0
1  2.0   NaN    NaN
2  3.0   NaN  300.0
3  NaN  40.0  400.0
4  5.0  50.0    NaN

Task 11 -> Q3

     A   B      C
2  3.0 NaN  300.0

Task 11 -> Q4

     A     B      C
0  1.0  10.0  100.0
1  2.0   1.0    1.0
2  3.0   1.0  300.0
3  1.0  40.0  400.0
4  5.0  50.0    1.0
5  1.0   1.0    1.0

Task 11 -> Q5

     A          B      C
0  NaN  10.000000  100.0
1  2.0  33.333333    NaN
2  3.0  33.333333  300.0
3  NaN  40.000000  400.0
4  5.0  50.000000    NaN
5  NaN  33.333333    NaN