In [1]:
import numpy as np 
import pandas as pd

In [2]:
# Exercise
# The tables below show how many hours each worker worked each day.
# Not every worker appears every day — this is intentional, so you must use .add(fill_value=0).

# Monday
# Worker	Hours
# Alice	     8
# Bob	     6
# David	     7

# Tuesday
# Worker	Hours
# Bob	     8
# Carol	     5
# David	     6

# Wednesday
# Worker	Hours
# Alice    	 7
# Carol	     8
# David	     5

In [3]:
# Task 1
# Create a pd.Series for each day using the tables above as your data.

Monday = pd.Series({ 
    'Alice': 8, 
    'Bob': 5,
    'David': 7
})

Tuesday = pd.Series({
    'Bob': 8, 
    'Carol': 5,
    'David': 6
})

Wednesday = pd.Series({
    'Alice': 7, 
    'Carol': 8,
    'David': 5
})
print(f'--- Monday ---\n{Monday}\n')
print(f'--- Tuesday ---\n{Tuesday}\n')
print(f'--- Wednesday ---\n{Wednesday}\n')

--- Monday ---
Alice    8
Bob      5
David    7
dtype: int64

--- Tuesday ---
Bob      8
Carol    5
David    6
dtype: int64

--- Wednesday ---
Alice    7
Carol    8
David    5
dtype: int64

In [4]:
# Task 2
# Combine all three Series into one total_hours Series showing each worker's total hours across the week.
#Use .add(fill_value=0) so missing days count as 0.

total_hours = Monday.add(Tuesday, fill_value=0).add(Wednesday, fill_value=0)
print(f'--- total_hours ---\n{total_hours.astype(int)}')

--- total_hours ---
Alice    15
Bob      13
Carol    13
David    18
dtype: int64

In [5]:
# Task 3 — Bonus ★
# Using total_hours, find which employee worked the most hours this week.

total_hours = Monday.add(Tuesday, fill_value=0).add(Wednesday, fill_value=0)
print(f'The employee worked the most hours this week is -> {total_hours.idxmax()} -- {total_hours.max()}')

The employee worked the most hours this week is -> David -- 18.0

In [6]:
# Task 4 — Bonus ★
# Build a DataFrame from the three shift tables — one row per worker, one column per day. Use 0 for days the worker did not work.

work_Table = {'Worker': ['Alice', 'Bob', 'Karol', 'David'],
        'MON': [8, 6, 0, 7],
        'TUE': [0, 8, 5, 6],
        'WED': [7, 0, 8, 5]}

df = pd.DataFrame(work_Table)

print(df)

  Worker  MON  TUE  WED
0  Alice    8    0    7
1    Bob    6    8    0
2  Karol    0    5    8
3  David    7    6    5

In [7]:
# Task 4 — Bonus ★
# Option 2

work_table_df = pd.read_csv('work.csv')
work_table_df

  WORKER  MON  TUE  WED
0  Alice    8    0    7
1    Bob    6    8    0
2  Carol    0    5    8
3  David    7    6    5

In [8]:
work_table_df = pd.read_csv('work.csv')
work_table_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   WORKER  4 non-null      object
 1   MON     4 non-null      int64
 2   TUE     4 non-null      int64
 3   WED     4 non-null      int64
dtypes: int64(3), object(1)
memory usage: 260.0+ bytes

In [9]:
work_table_df = pd.read_csv('work.csv')
work_table_df['Total_Hours'] = work_table_df['MON'] + work_table_df['TUE'] + work_table_df['WED']
work_table_df

  WORKER  MON  TUE  WED  Total_Hours
0  Alice    8    0    7           15
1    Bob    6    8    0           14
2  Carol    0    5    8           13
3  David    7    6    5           18