In [1]:
import numpy as np 
import pandas as pd
from IPython.display import display

In [2]:
import io
import pandas as pd

# 1. Define your CSV string
csv_string = """Name,Age,City
Alice,25,New York
Bob,30,Los Angeles
Charlie,35,Chicago"""

# 2. Convert string to a file-like object and read it
df = pd.read_csv(io.StringIO(csv_string))
        
df

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

In [3]:
tips_df = pd.read_csv('tips.csv')
tips_df

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251
...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672

In [4]:
tips_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   total_bill        244 non-null    float64
 1   tip               244 non-null    float64
 2   sex               244 non-null    object
 3   smoker            244 non-null    object
 4   day               244 non-null    object
 5   time              244 non-null    object
 6   size              244 non-null    int64
 7   price_per_person  244 non-null    float64
 8   Payer Name        244 non-null    object
 9   CC Number         244 non-null    int64
 10  Payment ID        244 non-null    object
dtypes: float64(3), int64(2), object(6)
memory usage: 21.1+ KB

In [5]:
tips_df = pd.read_csv('tips.csv')
print(tips_df.columns)
print(tips_df.index)

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size',
       'price_per_person', 'Payer Name', 'CC Number', 'Payment ID'],
      dtype='object')
RangeIndex(start=0, stop=244, step=1)

In [6]:
# from IPython.display import display
tips_df = pd.read_csv('tips.csv')
print(len(tips_df))
print()
display('head', tips_df.head())
print()
display('tail', tips_df.tail(5))

244

'head'

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251

'tail'

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672

In [7]:
tips_df = pd.read_csv('tips.csv')
tips_df.describe().transpose()
# percentile
#      3        15       23        31
# 1, 2, 8, 9, 14, 20, 22, 25, 29, 30

#      3          26       27.5          31
# 1, 2, 23, 24, 25, 26, 27,   28, 29, 30

,count,mean,std,min,25%,50%,75%,max
total_bill,244.0,1.978594e+01,8.902412e+00,3.070000e+00,1.334750e+01,1.779500e+01,2.412750e+01,5.081000e+01
tip,244.0,2.998279e+00,1.383638e+00,1.000000e+00,2.000000e+00,2.900000e+00,3.562500e+00,1.000000e+01
size,244.0,2.569672e+00,9.510998e-01,1.000000e+00,2.000000e+00,2.000000e+00,3.000000e+00,6.000000e+00
price_per_person,244.0,7.888197e+00,2.914234e+00,2.880000e+00,5.800000e+00,7.255000e+00,9.390000e+00,2.027000e+01
CC Number,244.0,2.563496e+15,2.369340e+15,6.040679e+10,3.040731e+13,3.525318e+15,4.553675e+15,6.596454e+15

In [8]:
tips_df = pd.read_csv('tips.csv')
display('1 column = series', tips_df['tip'])  # display(tips_df['tip'].to_frame())
print()
display('2 columns = df', tips_df[ ['tip', 'day'] ])

'1 column = series'

0      1.01
1      1.66
2      3.50
3      3.31
4      3.61
       ...
239    5.92
240    2.00
241    2.00
242    1.75
243    3.00
Name: tip, Length: 244, dtype: float64

'2 columns = df'

      tip   day
0    1.01   Sun
1    1.66   Sun
2    3.50   Sun
3    3.31   Sun
4    3.61   Sun
..    ...   ...
239  5.92   Sat
240  2.00   Sat
241  2.00   Sat
242  1.75   Sat
243  3.00  Thur

[244 rows x 2 columns]

In [9]:
tips_df = pd.read_csv('tips.csv')
tips_df['Sum With Tip'] = tips_df['tip'] + tips_df['total_bill']
display(tips_df)

# create column called "Tip Percentage" i.e. 300 and put 30 => %10

tips_df = pd.read_csv('tips.csv')
tips_df['Tip Percentage'] = (tips_df['tip'] / tips_df['total_bill'] * 100).round(1)
display(tips_df)

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,Sum With Tip
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959,18.00
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608,12.00
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458,24.51
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260,26.99
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251,28.20
...,...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657,34.95
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766,29.18
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880,24.67
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17,19.57
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672,21.78

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,Tip Percentage
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959,5.9
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608,16.1
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458,16.7
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260,14.0
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251,14.7
...,...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657,20.4
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766,7.4
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880,8.8
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17,9.8
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672,16.0

In [10]:
df = pd.read_csv('tips.csv')
# df = df.set_index('Payment ID')
# df = df.drop('Sun4608', axis=0) # drop by index
df = df.set_index('Payer Name')
display(df.loc['Michael Avila'].to_frame().T)  # by key
# df = df.drop('Michael Avila', axis=0)  # drop by index 
#df.reset_index()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,CC Number,Payment ID
Michael Avila,29.03,5.92,Male,No,Sat,Dinner,3,9.68,5296068606052842,Sat2657

In [11]:
# make Payment ID as index
# display all rows with Sun2959
# reset the index

# df = pd.read_csv('tips.csv')
# df.set_index('Payment ID')
# display(df.loc['Sun2959'])
# df = df.reset_index


# set index as time
# display all rows with index 'Dinner'
# drop all rows with index Dinner
# drop column smoker
# display df

df = pd.read_csv('tips.csv')
df = df.set_index('time')
display(df.loc['Dinner'])
df = df.drop('Dinner', axis=0) 
df = df.drop('smoker', axis=1) 
print(df)
display(df)

,total_bill,tip,sex,smoker,day,size,price_per_person,Payer Name,CC Number,Payment ID
time,,,,,,,,,,
Dinner,16.99,1.01,Female,No,Sun,2,8.49,Christy Cunningham,3560325168603410,Sun2959
Dinner,10.34,1.66,Male,No,Sun,3,3.45,Douglas Tucker,4478071379779230,Sun4608
Dinner,21.01,3.50,Male,No,Sun,3,7.00,Travis Walters,6011812112971322,Sun4458
Dinner,23.68,3.31,Male,No,Sun,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
Dinner,24.59,3.61,Female,No,Sun,4,6.15,Tonya Carter,4832732618637221,Sun2251
...,...,...,...,...,...,...,...,...,...,...
Dinner,29.03,5.92,Male,No,Sat,3,9.68,Michael Avila,5296068606052842,Sat2657
Dinner,27.18,2.00,Female,Yes,Sat,2,13.59,Monica Sanders,3506806155565404,Sat1766
Dinner,22.67,2.00,Male,Yes,Sat,2,11.34,Keith Wong,6011891618747196,Sat3880
Dinner,17.82,1.75,Male,No,Sat,2,8.91,Dennis Dixon,4375220550950,Sat17
Dinner,18.78,3.00,Female,No,Thur,2,9.39,Michelle Hardin,3511451626698139,Thur672

       total_bill   tip     sex   day  size  price_per_person  \
time
Lunch       27.20  4.00    Male  Thur     4              6.80
Lunch       22.76  3.00    Male  Thur     2             11.38
Lunch       17.29  2.71    Male  Thur     2              8.64
Lunch       19.44  3.00    Male  Thur     2              9.72
Lunch       16.66  3.40    Male  Thur     2              8.33
...           ...   ...     ...   ...   ...               ...
Lunch        8.58  1.92    Male   Fri     1              8.58
Lunch       15.98  3.00  Female   Fri     3              5.33
Lunch       13.42  1.58    Male   Fri     2              6.71
Lunch       16.27  2.50  Female   Fri     2              8.14
Lunch       10.09  2.00  Female   Fri     2              5.04

              Payer Name         CC Number Payment ID
time
Lunch         John Davis    30344778738589   Thur4924
Lunch         Chris Hahn  3591887177014031   Thur2863
Lunch         Brian Diaz  4759290988169738   Thur9501
Lunch       Louis Torres    38848369968464   Thur6453
Lunch     William Martin  4550549048402707   Thur8232
...                  ...               ...        ...
Lunch     Jason Lawrence  3505302934650403    Fri6624
Lunch        Mary Rivera  5343428579353069    Fri6014
Lunch  Ronald Vaughn DVM   341503466406403    Fri5959
Lunch     Whitney Arnold  3579111947217428    Fri6665
Lunch         Ruth Weiss  5268689490381635    Fri6359

[68 rows x 9 columns]

,total_bill,tip,sex,day,size,price_per_person,Payer Name,CC Number,Payment ID
time,,,,,,,,,
Lunch,27.20,4.00,Male,Thur,4,6.80,John Davis,30344778738589,Thur4924
Lunch,22.76,3.00,Male,Thur,2,11.38,Chris Hahn,3591887177014031,Thur2863
Lunch,17.29,2.71,Male,Thur,2,8.64,Brian Diaz,4759290988169738,Thur9501
Lunch,19.44,3.00,Male,Thur,2,9.72,Louis Torres,38848369968464,Thur6453
Lunch,16.66,3.40,Male,Thur,2,8.33,William Martin,4550549048402707,Thur8232
...,...,...,...,...,...,...,...,...,...
Lunch,8.58,1.92,Male,Fri,1,8.58,Jason Lawrence,3505302934650403,Fri6624
Lunch,15.98,3.00,Female,Fri,3,5.33,Mary Rivera,5343428579353069,Fri6014
Lunch,13.42,1.58,Male,Fri,2,6.71,Ronald Vaughn DVM,341503466406403,Fri5959
Lunch,16.27,2.50,Female,Fri,2,8.14,Whitney Arnold,3579111947217428,Fri6665
Lunch,10.09,2.00,Female,Fri,2,5.04,Ruth Weiss,5268689490381635,Fri6359

In [12]:
df = pd.read_csv('tips.csv')
df = df.set_index('Payer Name')

# loc  --> index
# iloc --> the i row

df.iloc[0:5]
df.iloc[4::-1]

,total_bill,tip,sex,smoker,day,time,size,price_per_person,CC Number,Payment ID
Payer Name,,,,,,,,,,
Tonya Carter,24.59,3.61,Female,No,Sun,Dinner,4,6.15,4832732618637221,Sun2251
Nathaniel Harris,23.68,3.31,Male,No,Sun,Dinner,2,11.84,4676137647685994,Sun5260
Travis Walters,21.01,3.50,Male,No,Sun,Dinner,3,7.00,6011812112971322,Sun4458
Douglas Tucker,10.34,1.66,Male,No,Sun,Dinner,3,3.45,4478071379779230,Sun4608
Christy Cunningham,16.99,1.01,Female,No,Sun,Dinner,2,8.49,3560325168603410,Sun2959

In [13]:
df = pd.read_csv('tips.csv')
df = df.set_index('Payer Name')
display(df.loc['Douglas Tucker': 'Tonya Carter'])  # like df.iloc[4:0:-1]
display(df.loc[ ['Douglas Tucker', 'Tonya Carter'] ])

,total_bill,tip,sex,smoker,day,time,size,price_per_person,CC Number,Payment ID
Payer Name,,,,,,,,,,
Douglas Tucker,10.34,1.66,Male,No,Sun,Dinner,3,3.45,4478071379779230,Sun4608
Travis Walters,21.01,3.50,Male,No,Sun,Dinner,3,7.00,6011812112971322,Sun4458
Nathaniel Harris,23.68,3.31,Male,No,Sun,Dinner,2,11.84,4676137647685994,Sun5260
Tonya Carter,24.59,3.61,Female,No,Sun,Dinner,4,6.15,4832732618637221,Sun2251

,total_bill,tip,sex,smoker,day,time,size,price_per_person,CC Number,Payment ID
Payer Name,,,,,,,,,,
Douglas Tucker,10.34,1.66,Male,No,Sun,Dinner,3,3.45,4478071379779230,Sun4608
Tonya Carter,24.59,3.61,Female,No,Sun,Dinner,4,6.15,4832732618637221,Sun2251

In [14]:
# load tips csv 
# make 'payment id' as index
# display
# display the first 5 using loc, and the first 5, using iloc
# display the first 5 in reverse, using iloc 

df = pd.read_csv('tips.csv')
df = df.set_index('Payment ID')
display(df)
display(df.loc['Sun2959':'Sun2251'])
display(df.iloc[4::-1])

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number
Payment ID,,,,,,,,,,
Sun2959,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410
Sun4608,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230
Sun4458,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322
Sun5260,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994
Sun2251,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221
...,...,...,...,...,...,...,...,...,...,...
Sat2657,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842
Sat1766,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404
Sat3880,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196
Sat17,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950
Thur672,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number
Payment ID,,,,,,,,,,
Sun2959,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410
Sun4608,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230
Sun4458,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322
Sun5260,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994
Sun2251,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number
Payment ID,,,,,,,,,,
Sun2251,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221
Sun5260,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994
Sun4458,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322
Sun4608,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230
Sun2959,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410

In [15]:
# create df consist of :
# 3 first rows and 2 last rows
# concat rows ------------------------------- union
df = pd.read_csv('tips.csv')
# df.loc[0:4]
pd.concat([df.head(3), df.tail(2)]) # index 0, 1, 2, 242, 243
# pd.concat([df.head(3), df.tail(2)], ignore_index=True) # index 0, 1, 2, 3, 4

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672

In [16]:
# Two separate DataFrames
# Concat cols --------------------------------------------------- join
df_left = pd.DataFrame({'Country': ['USA', 'Canada']})
df_right = pd.DataFrame({'GDP': [20.5, 1.7]})

display(df_left)
display(df_right)

# Concatenate them side-by-side as columns -- join
combined_df = pd.concat([df_left, df_right], axis=1)
display(combined_df)

  Country
0     USA
1  Canada

    GDP
0  20.5
1   1.7

  Country   GDP
0     USA  20.5
1  Canada   1.7

In [17]:
countries = ['USA', 'Canada', 'Mexico']
years = [1776, 1867, 1821]
population = [328, 38, 126]
gdp = [20.5, 1.7, 1.22]
countries_df = pd.DataFrame({
    'Country': countries,
    'Year': years,
    'Population': population,
    'GDP': gdp
})
countries_df = countries_df.set_index('Country')
display(countries_df)
display(countries_df['Population'] > 50)

# countries_df[ [True, False, True] ]  -- selects 2 rows --> only rows with True

display(countries_df[ countries_df['Population'] > 50 ])

# & | ~ Between

         Year  Population    GDP
Country
USA      1776         328  20.50
Canada   1867          38   1.70
Mexico   1821         126   1.22

Country
USA        True
Canada    False
Mexico     True
Name: Population, dtype: bool

         Year  Population    GDP
Country
USA      1776         328  20.50
Mexico   1821         126   1.22

In [18]:
# load csv tips
# 1) select all smoker rows == True
# 2) Bonus: select all rows were tips was more than 10%
# 3) select all rows where total_bill between 10 and 20
# 4) select all rows where total_bill NOT between 10 and 20

# & | ~ Between 

df = pd.read_csv('tips.csv')
display( df[ df['smoker'] == 'Yes' ].head(3))
display( df[ 100 * df['tip'] / df['total_bill'] > 10 ].head(3))
display( df[ df['total_bill'].between(10, 20) ].head(3))
display( df[ ~df['total_bill'].between(10, 20) ].head(3))

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
56,38.01,3.00,Male,Yes,Sat,Dinner,4,9.50,James Christensen DDS,349793629453226,Sat8903
58,11.24,1.76,Male,Yes,Sat,Dinner,2,5.62,Troy Guerrero,3560782621035582,Sat6683
60,20.29,3.21,Male,Yes,Sat,Dinner,2,10.14,Anthony Mclean,347614304015027,Sat2353

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
8,15.04,1.96,Male,No,Sun,Dinner,2,7.52,Joseph Mcdonald,3522866365840377,Sun6820

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251

In [19]:
# get last 4 digit from CC Number
# df['CC Number 4'] = len(df['CC Number']) # does not work

df = pd.read_csv('tips.csv')
def last_four(num):
    return str(num)[-4:]
    
display(last_four(3560325168603410))

display(df.head(3))
df['4 last digit'] = df['CC Number'].apply(last_four)
df = df['4 last digit'].to_frame()
display(df.head(3))

print()
# create column Payer First Name
# use column Payer Name + apply
# df['Payer First Name']

# option 1
# df = pd.read_csv('tips.csv')
# df['first_name'] = df['Payer Name'].str.split(' ').str[0]
# display(df)

# option 2
df = pd.read_csv('tips.csv')
def First_Name(first):
    return first.split(' ')[0]
    
display(First_Name('Christy Cunningham'))

display(df.head(3))
df['Payer First Name'] = df['Payer Name'].apply(First_Name)
df['Payer First Name'].to_frame()
display(df.head(3))

'3410'

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458

  4 last digit
0         3410
1         9230
2         1322

'Christy'

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,Payer First Name
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959,Christy
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608,Douglas
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458,Travis

In [20]:
# get last 4 digit from CC Number
tips_df = pd.read_csv('tips.csv')

# apply won't help since it works on 1 column only
#  df['Generous'] = tip/total_bill > 10% ? "Generous" else "Not Generous"

# solution -- np.vectorize() --> get few columns and run a function 
# np.vectorize() = apply with few columns
def is_generous(total_bill, tip):
    if (tip / total_bill) * 100 > 10:
        return 'Generous'
    else:       
        return 'Not Generous'

display(tips_df.head())
tips_df['category'] = np.vectorize(is_generous)(df['total_bill'], tips_df['tip'])
tips_df.tail()
# tips_df[ tips_df['category'] == 'Generous' ]

# create a new column 'table_type'
# if size > 4 then Extra Large else size > 2 then large else if 2 => Regular, else 1 -- Single
# if smoker - Smokers, else Healthy
#   Healthy Regular 
#   Smokers large


def Dimensions(size, smoker):
    match smoker:
        case 'No':
            health_status = 'Healthy'
        case 'Yes':
            health_status = 'smokers'
        case _:
            health_status = 'Unknown'

    match size:
        case 5 | 6: 
            size_status = 'Extra Large'
        case 4 | 3: 
            size_status = 'Large'
        case 2: 
            size_status = 'Regular'
        case _: 
            size_status = 'Single'
            
    return f"{health_status} - {size_status}"
  
display(tips_df.head(5))
tips_df['table_type'] = np.vectorize(Dimensions)(df['size'], tips_df['smoker'])
tips_df.tail(5)

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,category
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959,Not Generous
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608,Generous
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458,Generous
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260,Generous
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251,Generous

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,category,table_type
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657,Generous,Healthy - Large
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766,Not Generous,smokers - Regular
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880,Not Generous,smokers - Regular
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17,Not Generous,Healthy - Regular
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672,Generous,Healthy - Regular