In [1]:
import io
import numpy as np 
import pandas as pd
from IPython.display import display

In [ ]:
# Exercise:
# Use the dataset below — a small orders table for a restaurant chain. 
# The data is provided as a CSV string so you don't need any files.

In [11]:
# Dataset — paste this into your notebook
csv_data = """order_id,customer,city,total_bill,tip,table_size
1,Alice,Tel Aviv,45.50,8.00,4
2,Bob,Haifa,22.30,3.50,2
3,Carol,Tel Aviv,67.80,12.00,6
4,David,Jerusalem,15.20,2.00,2
5,Eve,Haifa,89.90,15.00,8
6,Frank,Tel Aviv,33.40,5.50,3
7,Grace,Jerusalem,51.00,9.00,4
8,Henry,Haifa,28.60,4.00,2
9,Iris,Tel Aviv,74.20,13.50,5
10,Jake,Jerusalem,19.80,2.50,2"""

# Task 1
# Load csv_data into a DataFrame using io.StringIO and pd.read_csv.
# Print .info() and .describe().transpose()
print(f'---- Task 1 ----')  
df = pd.read_csv(io.StringIO(csv_data))
display(df)    
display(df.info())
display(df.describe().transpose())

   order_id customer       city  total_bill   tip  table_size
0         1    Alice   Tel Aviv        45.5   8.0           4
1         2      Bob      Haifa        22.3   3.5           2
2         3    Carol   Tel Aviv        67.8  12.0           6
3         4    David  Jerusalem        15.2   2.0           2
4         5      Eve      Haifa        89.9  15.0           8
5         6    Frank   Tel Aviv        33.4   5.5           3
6         7    Grace  Jerusalem        51.0   9.0           4
7         8    Henry      Haifa        28.6   4.0           2
8         9     Iris   Tel Aviv        74.2  13.5           5
9        10     Jake  Jerusalem        19.8   2.5           2

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   order_id    10 non-null     int64
 1   customer    10 non-null     object
 2   city        10 non-null     object
 3   total_bill  10 non-null     float64
 4   tip         10 non-null     float64
 5   table_size  10 non-null     int64
dtypes: float64(2), int64(2), object(2)
memory usage: 612.0+ bytes

None

            count   mean        std   min     25%    50%    75%   max
order_id     10.0   5.50   3.027650   1.0   3.250   5.50   7.75  10.0
total_bill   10.0  44.77  25.530159  15.2  23.875  39.45  63.60  89.9
tip          10.0   7.50   4.743416   2.0   3.625   6.75  11.25  15.0
table_size   10.0   3.80   2.043961   2.0   2.000   3.50   4.75   8.0

In [84]:
# Task 2
# Add a column price_per_person that holds the bill divided by the table size, rounded to 2 decimal places.
# Formula: total_bill / table_size
df = pd.read_csv(io.StringIO(csv_data))
print(f'---- Task 2 ----')    
df['price_per_person']= (df['total_bill'] / df['table_size']).round(2)
display(df)

print()
# Task 3
# Filter the DataFrame to show only orders where price_per_person is greater than 12
print(f'---- Task 4 ----') 
display(df[ df['price_per_person'] > 12])

---- Task 2 ----

,order_id,customer,city,total_bill,tip,table_size,price_per_person
0,1,Alice,Tel Aviv,45.5,8.0,4,11.38
1,2,Bob,Haifa,22.3,3.5,2,11.15
2,3,Carol,Tel Aviv,67.8,12.0,6,11.30
3,4,David,Jerusalem,15.2,2.0,2,7.60
4,5,Eve,Haifa,89.9,15.0,8,11.24
5,6,Frank,Tel Aviv,33.4,5.5,3,11.13
6,7,Grace,Jerusalem,51.0,9.0,4,12.75
7,8,Henry,Haifa,28.6,4.0,2,14.30
8,9,Iris,Tel Aviv,74.2,13.5,5,14.84
9,10,Jake,Jerusalem,19.8,2.5,2,9.90

---- Task 4 ----

,order_id,customer,city,total_bill,tip,table_size,price_per_person
6,7,Grace,Jerusalem,51.0,9.0,4,12.75
7,8,Henry,Haifa,28.6,4.0,2,14.30
8,9,Iris,Tel Aviv,74.2,13.5,5,14.84

In [83]:
# Task 4
# Use .apply() to create a column table_type: 'Large' if table_size >= 4, otherwise 'Small'
print(f'---- Task 4 ----')  
df = pd.read_csv(io.StringIO(csv_data))
def size(table_size):
    if table_size >= 4:
        return 'Large'
    return 'Small'

df['table_type'] = df['table_size'].apply(size)
display(df)

---- Task 4 ----

   order_id customer       city  total_bill   tip  table_size table_type
0         1    Alice   Tel Aviv        45.5   8.0           4      Large
1         2      Bob      Haifa        22.3   3.5           2      Small
2         3    Carol   Tel Aviv        67.8  12.0           6      Large
3         4    David  Jerusalem        15.2   2.0           2      Small
4         5      Eve      Haifa        89.9  15.0           8      Large
5         6    Frank   Tel Aviv        33.4   5.5           3      Small
6         7    Grace  Jerusalem        51.0   9.0           4      Large
7         8    Henry      Haifa        28.6   4.0           2      Small
8         9     Iris   Tel Aviv        74.2  13.5           5      Large
9        10     Jake  Jerusalem        19.8   2.5           2      Small

In [82]:
# Task 5
# Set customer as the index. Then use .loc[] to select the rows from Alice to Carol
print(f'---- Task 5 ----')   
df = pd.read_csv(io.StringIO(csv_data))
df = df.set_index('customer')
display(df)
display(df.loc['Alice':'Carol'])

---- Task 5 ----

          order_id       city  total_bill   tip  table_size
customer
Alice            1   Tel Aviv        45.5   8.0           4
Bob              2      Haifa        22.3   3.5           2
Carol            3   Tel Aviv        67.8  12.0           6
David            4  Jerusalem        15.2   2.0           2
Eve              5      Haifa        89.9  15.0           8
Frank            6   Tel Aviv        33.4   5.5           3
Grace            7  Jerusalem        51.0   9.0           4
Henry            8      Haifa        28.6   4.0           2
Iris             9   Tel Aviv        74.2  13.5           5
Jake            10  Jerusalem        19.8   2.5           2

          order_id      city  total_bill   tip  table_size
customer
Alice            1  Tel Aviv        45.5   8.0           4
Bob              2     Haifa        22.3   3.5           2
Carol            3  Tel Aviv        67.8  12.0           6

In [99]:
# Task 6
# Use pd.concat with axis=0 to create a new DataFrame containing the first 3 rows and the last 3 rows of the original DataFrame.
# Reset the index
print(f'---- Task 6 ----')  
df = pd.read_csv(io.StringIO(csv_data))
display(pd.concat([df.head(3), df.tail(3)], axis=0)) # index 0, 1, 2, 7, 8, 9
print()
display(pd.concat([df.head(3), df.tail(3)], axis=0, ignore_index=True)) # index 0, 1, 2, 3, 4, 5

---- Task 6 ----

   order_id customer       city  total_bill   tip  table_size
0         1    Alice   Tel Aviv        45.5   8.0           4
1         2      Bob      Haifa        22.3   3.5           2
2         3    Carol   Tel Aviv        67.8  12.0           6
7         8    Henry      Haifa        28.6   4.0           2
8         9     Iris   Tel Aviv        74.2  13.5           5
9        10     Jake  Jerusalem        19.8   2.5           2

   order_id customer       city  total_bill   tip  table_size
0         1    Alice   Tel Aviv        45.5   8.0           4
1         2      Bob      Haifa        22.3   3.5           2
2         3    Carol   Tel Aviv        67.8  12.0           6
3         8    Henry      Haifa        28.6   4.0           2
4         9     Iris   Tel Aviv        74.2  13.5           5
5        10     Jake  Jerusalem        19.8   2.5           2

In [110]:
# Task 7
# Use np.vectorize to create a column value_label:
# 'High Value' if total_bill > 50 and tip > 10%, otherwise 'Standard'
print(f'---- Task 7 ----')  
df = pd.read_csv(io.StringIO(csv_data))
def value(total_bill, tip):
    if (total_bill < 50) and (tip / total_bill) * 100 > 10:
        return 'High Value'
    return 'Standard'    

df['value_label'] = np.vectorize(value)(df['total_bill'], df['tip'])
display(df)

---- Task 7 ----

   order_id customer       city  total_bill   tip  table_size value_label
0         1    Alice   Tel Aviv        45.5   8.0           4  High Value
1         2      Bob      Haifa        22.3   3.5           2  High Value
2         3    Carol   Tel Aviv        67.8  12.0           6    Standard
3         4    David  Jerusalem        15.2   2.0           2  High Value
4         5      Eve      Haifa        89.9  15.0           8    Standard
5         6    Frank   Tel Aviv        33.4   5.5           3  High Value
6         7    Grace  Jerusalem        51.0   9.0           4    Standard
7         8    Henry      Haifa        28.6   4.0           2  High Value
8         9     Iris   Tel Aviv        74.2  13.5           5    Standard
9        10     Jake  Jerusalem        19.8   2.5           2  High Value

In [156]:
# Task 8
# Use .iloc[] to select the last 3 rows of the DataFrame, then use .iloc[] again to select rows at positions 2, 4, and 6
print(f'---- Task 8 ----')  
df = pd.read_csv(io.StringIO(csv_data))
display(df.iloc[-3:])

display(df.iloc[[2, 4, 6]])

---- Task 8 ----

   order_id customer       city  total_bill   tip  table_size
7         8    Henry      Haifa        28.6   4.0           2
8         9     Iris   Tel Aviv        74.2  13.5           5
9        10     Jake  Jerusalem        19.8   2.5           2

   order_id customer       city  total_bill   tip  table_size
2         3    Carol   Tel Aviv        67.8  12.0           6
4         5      Eve      Haifa        89.9  15.0           8
6         7    Grace  Jerusalem        51.0   9.0           4