In [1]:
import pandas as pd
import numpy  as np
from IPython.display import display

In [2]:
df = pd.read_csv('mpg.csv')
display(df)

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86,2790,15.6,82,1,ford mustang gl
394,44.0,4,97.0,52,2130,24.6,82,2,vw pickup
395,32.0,4,135.0,84,2295,11.6,82,1,dodge rampage
396,28.0,4,120.0,79,2625,18.6,82,1,ford ranger
397,31.0,4,119.0,82,2720,19.4,82,1,chevy s-10

In [3]:
display(df.describe().T)
print()
display(df.info())

,count,mean,std,min,25%,50%,75%,max
mpg,398.0,23.514573,7.815984,9.0,17.500,23.0,29.000,46.6
cylinders,398.0,5.454774,1.701004,3.0,4.000,4.0,8.000,8.0
displacement,398.0,193.425879,104.269838,68.0,104.250,148.5,262.000,455.0
weight,398.0,2970.424623,846.841774,1613.0,2223.750,2803.5,3608.000,5140.0
acceleration,398.0,15.568090,2.757689,8.0,13.825,15.5,17.175,24.8
model_year,398.0,76.010050,3.697627,70.0,73.000,76.0,79.000,82.0
origin,398.0,1.572864,0.802055,1.0,1.000,1.0,2.000,3.0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    398 non-null    object
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64
 7   origin        398 non-null    int64
 8   name          398 non-null    object
dtypes: float64(3), int64(4), object(2)
memory usage: 28.1+ KB

None

In [4]:
# df.groupby('model_year').mean(numeric_only=True)
# df_mean_per_group_mpg.loc[70:75].tail(2)
df_mean_per_group_mpg = df.groupby('model_year').mean('model_year')
display(df_mean_per_group_mpg['mpg'].to_frame())
display(df_mean_per_group_mpg.head(6).tail(3))

                  mpg
model_year
70          17.689655
71          21.250000
72          18.714286
73          17.100000
74          22.703704
75          20.266667
76          21.573529
77          23.375000
78          24.061111
79          25.093103
80          33.696552
81          30.334483
82          31.709677

,mpg,cylinders,displacement,weight,acceleration,origin
model_year,,,,,,
73,17.100000,6.375000,256.875000,3419.025000,14.312500,1.375000
74,22.703704,5.259259,171.740741,2877.925926,16.203704,1.666667
75,20.266667,5.600000,205.533333,3176.800000,16.050000,1.466667

In [5]:
df_mean_per_group_mpg = df.groupby('model_year').max(numeric_only=True)
display(df_mean_per_group_mpg)

print()
df['model_year'].value_counts().sort_index().to_frame()

             mpg  cylinders  displacement  weight  acceleration  origin
model_year
70          27.0          8         455.0    4732          20.5       3
71          35.0          8         400.0    5140          20.5       3
72          28.0          8         429.0    4633          23.5       3
73          29.0          8         455.0    4997          21.0       3
74          32.0          8         350.0    4699          21.0       3
75          33.0          8         400.0    4668          21.0       3
76          33.0          8         351.0    4380          22.2       3
77          36.0          8         400.0    4335          19.0       3
78          43.1          8         318.0    4080          21.5       3
79          37.3          8         360.0    4360          24.8       3
80          46.6          6         225.0    3381          23.7       3
81          39.1          8         350.0    3725          20.7       3
82          44.0          6         262.0    3035          24.6       3

            count
model_year
70             29
71             28
72             28
73             40
74             27
75             30
76             34
77             28
78             36
79             29
80             29
81             29
82             31

In [6]:
# a) find the 5 highest mpg mean value + year (group by year)
#   solutions:
#   1. find the mean of mpg per year.
#   2. find the five 5 years which the mean mpg was the highest.

highest_mpg = df.groupby('model_year').mean('model_year').nlargest(5, 'mpg')
display(highest_mpg['mpg'].to_frame())

mean_of_mpg = df.groupby('model_year').mean(numeric_only=True)
display(mean_of_mpg['mpg'].to_frame())

# b) find the lowest acceleration per cylinder ?

lowest_acceleration = df.groupby('cylinders').mean(numeric_only=True).nsmallest(1, 'acceleration')
display(lowest_acceleration['acceleration'].to_frame())

# c) what is the max weight per origin?
df_mean_per_group_mpg = df.groupby('origin').max('weight')
display(df_mean_per_group_mpg['weight'].max())

                  mpg
model_year
80          33.696552
82          31.709677
81          30.334483
79          25.093103
78          24.061111

                  mpg
model_year
70          17.689655
71          21.250000
72          18.714286
73          17.100000
74          22.703704
75          20.266667
76          21.573529
77          23.375000
78          24.061111
79          25.093103
80          33.696552
81          30.334483
82          31.709677

           acceleration
cylinders
8              12.95534

5140

In [7]:
new_df = df.groupby(['model_year', 'cylinders', 'origin']).mean(numeric_only=True)
display(new_df)
display(new_df.loc[[(81, 8, 1)]])

# 1
# max weight of group origin 2 year 82 cylidners 4 -- group by + loc
new_df = df.groupby(['model_year', 'cylinders', 'origin']).mean(numeric_only=True)
display(new_df)
display(new_df['weight'].loc[[(82, 4, 2)]].max())


# 2 bonus
# bring the mean value group by model_year and cylinder --> only for cylidners 6, 8
df[(df['cylinders'] == 4) | (df['cylinders'] == 6)]
df[df['cylinders'].isin([4, 6])]  # better 

# filter before group-by !!!
df[df['cylinders'].isin([4, 6])].groupby(['model_year', 'cylinders']).mean(numeric_only=True)

                                   mpg  displacement       weight  \
model_year cylinders origin
70         4         2       25.200000    107.800000  2309.200000
                     3       25.500000    105.000000  2251.000000
           6         1       20.500000    199.000000  2710.500000
           8         1       14.111111    367.555556  3940.055556
71         4         1       24.800000    118.200000  2178.600000
...                                ...           ...          ...
81         8         1       26.600000    350.000000  3725.000000
82         4         1       29.647059    128.470588  2585.882353
                     2       40.000000    101.000000  2055.000000
                     3       34.888889    103.777778  2132.777778
           6         1       28.333333    225.000000  2931.666667

                             acceleration
model_year cylinders origin
70         4         2          16.500000
                     3          14.750000
           6         1          15.500000
           8         1          11.194444
71         4         1          17.600000
...                                   ...
81         8         1          19.000000
82         4         1          16.782353
                     2          19.950000
                     3          15.833333
           6         1          16.033333

[76 rows x 4 columns]

                              mpg  displacement  weight  acceleration
model_year cylinders origin
81         8         1       26.6         350.0  3725.0          19.0

                                   mpg  displacement       weight  \
model_year cylinders origin
70         4         2       25.200000    107.800000  2309.200000
                     3       25.500000    105.000000  2251.000000
           6         1       20.500000    199.000000  2710.500000
           8         1       14.111111    367.555556  3940.055556
71         4         1       24.800000    118.200000  2178.600000
...                                ...           ...          ...
81         8         1       26.600000    350.000000  3725.000000
82         4         1       29.647059    128.470588  2585.882353
                     2       40.000000    101.000000  2055.000000
                     3       34.888889    103.777778  2132.777778
           6         1       28.333333    225.000000  2931.666667

                             acceleration
model_year cylinders origin
70         4         2          16.500000
                     3          14.750000
           6         1          15.500000
           8         1          11.194444
71         4         1          17.600000
...                                   ...
81         8         1          19.000000
82         4         1          16.782353
                     2          19.950000
                     3          15.833333
           6         1          16.033333

[76 rows x 4 columns]

2055.0

                            mpg  displacement       weight  acceleration  \
model_year cylinders
70         4          25.285714    107.000000  2292.571429     16.000000
           6          20.500000    199.000000  2710.500000     15.500000
71         4          27.461538    101.846154  2056.384615     16.961538
           6          18.000000    243.375000  3171.875000     14.750000
72         4          23.428571    111.535714  2382.642857     17.214286
73         4          22.727273    109.272727  2338.090909     17.136364
           6          19.000000    212.250000  2917.125000     15.687500
74         4          27.800000     96.533333  2151.466667     16.400000
           6          17.857143    230.428571  3320.000000     16.857143
75         4          25.250000    114.833333  2489.250000     15.833333
           6          17.583333    233.750000  3398.333333     17.708333
76         4          26.766667    106.333333  2306.600000     16.866667
           6          20.000000    221.400000  3349.600000     17.000000
77         4          29.107143    106.500000  2205.071429     16.064286
           6          19.500000    220.400000  3383.000000     16.900000
78         4          29.576471    112.117647  2296.764706     16.282353
           6          19.066667    213.250000  3314.166667     16.391667
79         4          31.525000    113.583333  2357.583333     15.991667
           6          22.950000    205.666667  3025.833333     15.433333
80         4          34.612000    111.000000  2360.080000     17.144000
           6          25.900000    196.500000  3145.500000     15.050000
81         4          32.814286    108.857143  2275.476190     16.466667
           6          23.428571    184.000000  3093.571429     15.442857
82         4          32.071429    118.571429  2402.321429     16.703571
           6          28.333333    225.000000  2931.666667     16.033333

                        origin
model_year cylinders
70         4          2.285714
           6          1.000000
71         4          1.923077
           6          1.000000
72         4          1.928571
73         4          2.000000
           6          1.250000
74         4          2.200000
           6          1.000000
75         4          2.166667
           6          1.000000
76         4          1.866667
           6          1.300000
77         4          1.857143
           6          1.400000
78         4          2.117647
           6          1.166667
79         4          1.583333
           6          1.000000
80         4          2.200000
           6          2.000000
81         4          2.095238
           6          1.714286
82         4          1.714286
           6          1.000000

In [8]:
df_year_cyl = df[df['cylinders'].isin([4, 6])].groupby(['model_year', 'cylinders']).mean(numeric_only=True)
# df_year_cyl.index

display(df_year_cyl)

print('xs - find in sub group where cylinders = 4')
display(df_year_cyl.xs(key=4, level='cylinders'))  # search for value 4 in cylidners

                            mpg  displacement       weight  acceleration  \
model_year cylinders
70         4          25.285714    107.000000  2292.571429     16.000000
           6          20.500000    199.000000  2710.500000     15.500000
71         4          27.461538    101.846154  2056.384615     16.961538
           6          18.000000    243.375000  3171.875000     14.750000
72         4          23.428571    111.535714  2382.642857     17.214286
73         4          22.727273    109.272727  2338.090909     17.136364
           6          19.000000    212.250000  2917.125000     15.687500
74         4          27.800000     96.533333  2151.466667     16.400000
           6          17.857143    230.428571  3320.000000     16.857143
75         4          25.250000    114.833333  2489.250000     15.833333
           6          17.583333    233.750000  3398.333333     17.708333
76         4          26.766667    106.333333  2306.600000     16.866667
           6          20.000000    221.400000  3349.600000     17.000000
77         4          29.107143    106.500000  2205.071429     16.064286
           6          19.500000    220.400000  3383.000000     16.900000
78         4          29.576471    112.117647  2296.764706     16.282353
           6          19.066667    213.250000  3314.166667     16.391667
79         4          31.525000    113.583333  2357.583333     15.991667
           6          22.950000    205.666667  3025.833333     15.433333
80         4          34.612000    111.000000  2360.080000     17.144000
           6          25.900000    196.500000  3145.500000     15.050000
81         4          32.814286    108.857143  2275.476190     16.466667
           6          23.428571    184.000000  3093.571429     15.442857
82         4          32.071429    118.571429  2402.321429     16.703571
           6          28.333333    225.000000  2931.666667     16.033333

                        origin
model_year cylinders
70         4          2.285714
           6          1.000000
71         4          1.923077
           6          1.000000
72         4          1.928571
73         4          2.000000
           6          1.250000
74         4          2.200000
           6          1.000000
75         4          2.166667
           6          1.000000
76         4          1.866667
           6          1.300000
77         4          1.857143
           6          1.400000
78         4          2.117647
           6          1.166667
79         4          1.583333
           6          1.000000
80         4          2.200000
           6          2.000000
81         4          2.095238
           6          1.714286
82         4          1.714286
           6          1.000000

xs - find in sub group where cylinders = 4

                  mpg  displacement       weight  acceleration    origin
model_year
70          25.285714    107.000000  2292.571429     16.000000  2.285714
71          27.461538    101.846154  2056.384615     16.961538  1.923077
72          23.428571    111.535714  2382.642857     17.214286  1.928571
73          22.727273    109.272727  2338.090909     17.136364  2.000000
74          27.800000     96.533333  2151.466667     16.400000  2.200000
75          25.250000    114.833333  2489.250000     15.833333  2.166667
76          26.766667    106.333333  2306.600000     16.866667  1.866667
77          29.107143    106.500000  2205.071429     16.064286  1.857143
78          29.576471    112.117647  2296.764706     16.282353  2.117647
79          31.525000    113.583333  2357.583333     15.991667  1.583333
80          34.612000    111.000000  2360.080000     17.144000  2.200000
81          32.814286    108.857143  2275.476190     16.466667  2.095238
82          32.071429    118.571429  2402.321429     16.703571  1.714286

In [9]:
df_year_cyl = df[df['cylinders'].isin([4, 6])].groupby(['model_year', 'cylinders']).mean(numeric_only=True)
# df_year_cyl.index

display(df_year_cyl)

print('swap index')
display(df_year_cyl.swaplevel().sort_index())

                            mpg  displacement       weight  acceleration  \
model_year cylinders
70         4          25.285714    107.000000  2292.571429     16.000000
           6          20.500000    199.000000  2710.500000     15.500000
71         4          27.461538    101.846154  2056.384615     16.961538
           6          18.000000    243.375000  3171.875000     14.750000
72         4          23.428571    111.535714  2382.642857     17.214286
73         4          22.727273    109.272727  2338.090909     17.136364
           6          19.000000    212.250000  2917.125000     15.687500
74         4          27.800000     96.533333  2151.466667     16.400000
           6          17.857143    230.428571  3320.000000     16.857143
75         4          25.250000    114.833333  2489.250000     15.833333
           6          17.583333    233.750000  3398.333333     17.708333
76         4          26.766667    106.333333  2306.600000     16.866667
           6          20.000000    221.400000  3349.600000     17.000000
77         4          29.107143    106.500000  2205.071429     16.064286
           6          19.500000    220.400000  3383.000000     16.900000
78         4          29.576471    112.117647  2296.764706     16.282353
           6          19.066667    213.250000  3314.166667     16.391667
79         4          31.525000    113.583333  2357.583333     15.991667
           6          22.950000    205.666667  3025.833333     15.433333
80         4          34.612000    111.000000  2360.080000     17.144000
           6          25.900000    196.500000  3145.500000     15.050000
81         4          32.814286    108.857143  2275.476190     16.466667
           6          23.428571    184.000000  3093.571429     15.442857
82         4          32.071429    118.571429  2402.321429     16.703571
           6          28.333333    225.000000  2931.666667     16.033333

                        origin
model_year cylinders
70         4          2.285714
           6          1.000000
71         4          1.923077
           6          1.000000
72         4          1.928571
73         4          2.000000
           6          1.250000
74         4          2.200000
           6          1.000000
75         4          2.166667
           6          1.000000
76         4          1.866667
           6          1.300000
77         4          1.857143
           6          1.400000
78         4          2.117647
           6          1.166667
79         4          1.583333
           6          1.000000
80         4          2.200000
           6          2.000000
81         4          2.095238
           6          1.714286
82         4          1.714286
           6          1.000000

swap index

                            mpg  displacement       weight  acceleration  \
cylinders model_year
4         70          25.285714    107.000000  2292.571429     16.000000
          71          27.461538    101.846154  2056.384615     16.961538
          72          23.428571    111.535714  2382.642857     17.214286
          73          22.727273    109.272727  2338.090909     17.136364
          74          27.800000     96.533333  2151.466667     16.400000
          75          25.250000    114.833333  2489.250000     15.833333
          76          26.766667    106.333333  2306.600000     16.866667
          77          29.107143    106.500000  2205.071429     16.064286
          78          29.576471    112.117647  2296.764706     16.282353
          79          31.525000    113.583333  2357.583333     15.991667
          80          34.612000    111.000000  2360.080000     17.144000
          81          32.814286    108.857143  2275.476190     16.466667
          82          32.071429    118.571429  2402.321429     16.703571
6         70          20.500000    199.000000  2710.500000     15.500000
          71          18.000000    243.375000  3171.875000     14.750000
          73          19.000000    212.250000  2917.125000     15.687500
          74          17.857143    230.428571  3320.000000     16.857143
          75          17.583333    233.750000  3398.333333     17.708333
          76          20.000000    221.400000  3349.600000     17.000000
          77          19.500000    220.400000  3383.000000     16.900000
          78          19.066667    213.250000  3314.166667     16.391667
          79          22.950000    205.666667  3025.833333     15.433333
          80          25.900000    196.500000  3145.500000     15.050000
          81          23.428571    184.000000  3093.571429     15.442857
          82          28.333333    225.000000  2931.666667     16.033333

                        origin
cylinders model_year
4         70          2.285714
          71          1.923077
          72          1.928571
          73          2.000000
          74          2.200000
          75          2.166667
          76          1.866667
          77          1.857143
          78          2.117647
          79          1.583333
          80          2.200000
          81          2.095238
          82          1.714286
6         70          1.000000
          71          1.000000
          73          1.250000
          74          1.000000
          75          1.000000
          76          1.300000
          77          1.400000
          78          1.166667
          79          1.000000
          80          2.000000
          81          1.714286
          82          1.000000

In [10]:
df_year_cyl = df[df['cylinders'].isin([4, 6])].groupby(['model_year', 'cylinders']).mean(numeric_only=True)
# df_year_cyl.index

display(df_year_cyl)

print('swap + look for cylinders = 4')
df_year_cyl.swaplevel().sort_index().loc[4]  # find cylinders 4 only

                            mpg  displacement       weight  acceleration  \
model_year cylinders
70         4          25.285714    107.000000  2292.571429     16.000000
           6          20.500000    199.000000  2710.500000     15.500000
71         4          27.461538    101.846154  2056.384615     16.961538
           6          18.000000    243.375000  3171.875000     14.750000
72         4          23.428571    111.535714  2382.642857     17.214286
73         4          22.727273    109.272727  2338.090909     17.136364
           6          19.000000    212.250000  2917.125000     15.687500
74         4          27.800000     96.533333  2151.466667     16.400000
           6          17.857143    230.428571  3320.000000     16.857143
75         4          25.250000    114.833333  2489.250000     15.833333
           6          17.583333    233.750000  3398.333333     17.708333
76         4          26.766667    106.333333  2306.600000     16.866667
           6          20.000000    221.400000  3349.600000     17.000000
77         4          29.107143    106.500000  2205.071429     16.064286
           6          19.500000    220.400000  3383.000000     16.900000
78         4          29.576471    112.117647  2296.764706     16.282353
           6          19.066667    213.250000  3314.166667     16.391667
79         4          31.525000    113.583333  2357.583333     15.991667
           6          22.950000    205.666667  3025.833333     15.433333
80         4          34.612000    111.000000  2360.080000     17.144000
           6          25.900000    196.500000  3145.500000     15.050000
81         4          32.814286    108.857143  2275.476190     16.466667
           6          23.428571    184.000000  3093.571429     15.442857
82         4          32.071429    118.571429  2402.321429     16.703571
           6          28.333333    225.000000  2931.666667     16.033333

                        origin
model_year cylinders
70         4          2.285714
           6          1.000000
71         4          1.923077
           6          1.000000
72         4          1.928571
73         4          2.000000
           6          1.250000
74         4          2.200000
           6          1.000000
75         4          2.166667
           6          1.000000
76         4          1.866667
           6          1.300000
77         4          1.857143
           6          1.400000
78         4          2.117647
           6          1.166667
79         4          1.583333
           6          1.000000
80         4          2.200000
           6          2.000000
81         4          2.095238
           6          1.714286
82         4          1.714286
           6          1.000000

swap + look for cylinders = 4

                  mpg  displacement       weight  acceleration    origin
model_year
70          25.285714    107.000000  2292.571429     16.000000  2.285714
71          27.461538    101.846154  2056.384615     16.961538  1.923077
72          23.428571    111.535714  2382.642857     17.214286  1.928571
73          22.727273    109.272727  2338.090909     17.136364  2.000000
74          27.800000     96.533333  2151.466667     16.400000  2.200000
75          25.250000    114.833333  2489.250000     15.833333  2.166667
76          26.766667    106.333333  2306.600000     16.866667  1.866667
77          29.107143    106.500000  2205.071429     16.064286  1.857143
78          29.576471    112.117647  2296.764706     16.282353  2.117647
79          31.525000    113.583333  2357.583333     15.991667  1.583333
80          34.612000    111.000000  2360.080000     17.144000  2.200000
81          32.814286    108.857143  2275.476190     16.466667  2.095238
82          32.071429    118.571429  2402.321429     16.703571  1.714286

In [11]:
agg_func = {'mpg': ['max', 'mean'], 'weight': ['std', 'mean'] }
df.agg(agg_func)

            mpg       weight
max   46.600000          NaN
mean  23.514573  2970.424623
std         NaN   846.841774

In [12]:
# Create the first DataFrame (Employees)
df_employees = pd.DataFrame({
    'emp_id': [1, 2, 3, 4, 5],
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'dept_id': [10, 20, 10, 30, 99]  # 99 does not exist in departments
})

# Create the second DataFrame (Departments)
df_departments = pd.DataFrame({
    'dept_id': [10, 20, 30, 40, 50],
    'dept_name': ['HR', 'Engineering', 'Marketing', 'Sales', 'Finance']
})

print("--- DataFrame 1: Employees ---")
display(df_employees)
print("--- DataFrame 2: Departments ---")
display(df_departments)

--- DataFrame 1: Employees ---

   emp_id     name  dept_id
0       1    Alice       10
1       2      Bob       20
2       3  Charlie       10
3       4    David       30
4       5      Eva       99

--- DataFrame 2: Departments ---

   dept_id    dept_name
0       10           HR
1       20  Engineering
2       30    Marketing
3       40        Sales
4       50      Finance

In [13]:
df_inner = pd.merge(df_employees, df_departments, on='dept_id', how='inner')
# what if col name is different?
# df_inner = pd.merge(df_employees, df_departments, left_on="dept_id", right_on="id", how='inner')

print("--- 1. Inner Join ---")
df_inner

--- 1. Inner Join ---

   emp_id     name  dept_id    dept_name
0       1    Alice       10           HR
1       2      Bob       20  Engineering
2       3  Charlie       10           HR
3       4    David       30    Marketing

In [14]:
df_left = pd.merge(df_employees, df_departments, on='dept_id', how='left')
print("--- 2. Left Join ---")
df_left

--- 2. Left Join ---

   emp_id     name  dept_id    dept_name
0       1    Alice       10           HR
1       2      Bob       20  Engineering
2       3  Charlie       10           HR
3       4    David       30    Marketing
4       5      Eva       99          NaN

In [15]:
df_right = pd.merge(df_employees, df_departments, on='dept_id', how='right')
df_right

   emp_id     name  dept_id    dept_name
0     1.0    Alice       10           HR
1     3.0  Charlie       10           HR
2     2.0      Bob       20  Engineering
3     4.0    David       30    Marketing
4     NaN      NaN       40        Sales
5     NaN      NaN       50      Finance

In [16]:
df_outer = pd.merge(df_employees, df_departments, on='dept_id', how='outer')
df_outer

   emp_id     name  dept_id    dept_name
0     1.0    Alice       10           HR
1     3.0  Charlie       10           HR
2     2.0      Bob       20  Engineering
3     4.0    David       30    Marketing
4     NaN      NaN       40        Sales
5     NaN      NaN       50      Finance
6     5.0      Eva       99          NaN

In [17]:
df_cross = pd.merge(df_employees, df_departments, how='cross')
print("--- 5. Cross Join (Truncated Output) ---")
df_cross.head(10)

--- 5. Cross Join (Truncated Output) ---

   emp_id   name  dept_id_x  dept_id_y    dept_name
0       1  Alice         10         10           HR
1       1  Alice         10         20  Engineering
2       1  Alice         10         30    Marketing
3       1  Alice         10         40        Sales
4       1  Alice         10         50      Finance
5       2    Bob         20         10           HR
6       2    Bob         20         20  Engineering
7       2    Bob         20         30    Marketing
8       2    Bob         20         40        Sales
9       2    Bob         20         50      Finance

In [18]:
import pandas as pd

# Table 1: Store Orders
orders = pd.DataFrame(
    {
        "order_id": [101, 102],
        "date": ["2026-06-01", "2026-06-02"],  # Order Date
        "status": ["Paid", "Paid"],  # Order Status
        "test": [1, 2]
    }
)

# Table 2: Shipping Shipments
shipping = pd.DataFrame(
    {
        "order_id": [101, 102],
        "date": ["2026-06-03", "2026-06-05"],  # Shipping Date
        "status": ["Shipped", "Delayed"]  # Shipping Status
    }
)

display(orders)
display(shipping)
# Merge the tables and create clear aliases for matching column names
final_report = pd.merge(
    orders, shipping, on="order_id", suffixes=("_order", "_ship")
)

display(final_report)

   order_id        date status  test
0       101  2026-06-01   Paid     1
1       102  2026-06-02   Paid     2

   order_id        date   status
0       101  2026-06-03  Shipped
1       102  2026-06-05  Delayed

   order_id  date_order status_order  test   date_ship status_ship
0       101  2026-06-01         Paid     1  2026-06-03     Shipped
1       102  2026-06-02         Paid     2  2026-06-05     Delayed

In [19]:
# Time
beer = pd.read_csv(r"RetailSales_BeerWineLiquor.csv")
display(beer)
beer.info()

           DATE  Total_Sales
0    1992-01-01         1509
1    1992-02-01         1541
2    1992-03-01         1597
3    1992-04-01         1675
4    1992-05-01         1822
..          ...          ...
335  2019-12-01         6630
336  2020-01-01         4388
337  2020-02-01         4533
338  2020-03-01         5562
339  2020-04-01         5207

[340 rows x 2 columns]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 340 entries, 0 to 339
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   DATE         340 non-null    object
 1   Total_Sales  340 non-null    int64
dtypes: int64(1), object(1)
memory usage: 5.4+ KB

In [20]:
beer['DATE'] = pd.to_datetime(beer['DATE'])
beer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 340 entries, 0 to 339
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   DATE         340 non-null    datetime64[ns]
 1   Total_Sales  340 non-null    int64
dtypes: datetime64[ns](1), int64(1)
memory usage: 5.4 KB

In [21]:

# beer.resample(rule='A') == creates the group

# resample: Groups the data into specified time intervals based on the rule provided
# rule='A':
# 'A' stands for "Annual", so the data will be resampled into yearly intervals
# The default behavior aggregates data at the end of each year (December 31st)
# mean(): After grouping the data into yearly intervals, this computes the mean for each group

#'A' | 'YE'	Year-end frequency	Dec 31, 2020; Dec 31, 2021
#'AS'	Year-start frequency	Jan 1, 2020; Jan 1, 2021
#'Q'	Quarter-end frequency	Mar 31, 2020; Jun 30, 2020
#'QS'	Quarter-start frequency	Jan 1, 2020; Apr 1, 2020
#'M' | 'ME'	Month-end frequency	Jan 31, 2020; Feb 29, 2020
#'MS'	Month-start frequency	Jan 1, 2020; Feb 1, 2020
#'W'	Week-end frequency	Jan 5, 2020; Jan 12, 2020
#'W-SUN'	Week ending on Sunday (default)	Jan 5, 2020; Jan 12, 2020
#'W-MON'	Week ending on Monday	Jan 6, 2020; Jan 13, 2020
#'D'	Daily frequency	Jan 1, 2020; Jan 2, 2020
#'H' |'h'	Hourly frequency	01:00, 02:00, 03:00
#'T' | 'min'	Minutely frequency	01:01, 01:02, 01:03
#'S'	Secondly frequency	01:01:01, 01:01:02
#'L'	Millisecond frequency	01:01:01.001, 01:01:01.002
#'U'	Microsecond frequency	01:01:01.000001, 01:01:01.000002
#'N'	Nanosecond frequency	01:01:01.000000001, 01:01:01.000000002

In [22]:
# beer instead of using str commands to seperate month + year ==> group by
# we can :
# 1 to_datetime
# 2 set_index
# 3 resample 

import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

beer = pd.read_csv(r"RetailSales_BeerWineLiquor.csv")
beer['DATE'] = pd.to_datetime(beer['DATE'])
beer.set_index('DATE', inplace=True)
beer.resample(rule='A').max(numeric_only=True) # resample + 'A' ==> group by year 


s = pd.Series(["12--Dec--2000"])
pd.to_datetime(s, format="%d--%b--%Y")

0   2000-12-12
dtype: datetime64[ns]

In [23]:
############################################################################################################################
##################################### BONUS -- EXTRA TOPIC  -- rare usage -- how to format multiple type of dates in same df
############################################################################################################################

# date-time
myser = pd.Series(['Nov 3, 1990', '2000-01-15', None]) 


######## same format
s = pd.Series(["12--Dec--2000"])
display(pd.to_datetime(s, format="%d--%b--%Y"))  # need to explain to python -- how the date str is built

######## so how to do 2 different formats?
formats = ['%b %d, %Y', '%Y-%m-%d']

# Function to try multiple formats
def parse_multiple_formats(date):
    for fmt in formats:
        try:
            return pd.to_datetime(date, format=fmt)
        except ValueError:
            continue
    return pd.NaT  # Return NaT if no formats match

# Apply the function to handle mixed formats
myser2 = pd.Series(['Nov 3, 1990', '2000-01-15', None])
myser2 = myser2.apply(parse_multiple_formats)

print(myser2)

0   2000-12-12
dtype: datetime64[ns]

0   1990-11-03
1   2000-01-15
2          NaT
dtype: datetime64[ns]

In [24]:
import pandas as pd

data = {
    'Date': [
        '2025-04-01', '2025-04-01', '2025-04-01',
        '2025-04-02', '2025-04-02', '2025-04-02',
        '2025-04-03', '2025-04-03', '2025-04-03',
        '2025-04-04', '2025-04-04', '2025-04-04',
        '2025-04-05', '2025-04-05'
    ],
    'Product': [
        'Apples', 'Oranges', 'Apples',
        'Oranges', 'Apples', 'Oranges',
        'Apples', 'Oranges', 'Apples',
        'Oranges', 'Apples', 'Oranges',
        'Apples', 'Oranges'
    ],
    'Sales': [
        100, 150, 130,
        120, 180, 100,
        90, 110, 85,
        140, 160, 130,
        200, 210
    ]
}

# export df to file

df.to_html('html1.html')
df.to_csv('csv1.csv')
df.to_excel('ex1.xlsx')

df = pd.DataFrame(data)
df

          Date  Product  Sales
0   2025-04-01   Apples    100
1   2025-04-01  Oranges    150
2   2025-04-01   Apples    130
3   2025-04-02  Oranges    120
4   2025-04-02   Apples    180
5   2025-04-02  Oranges    100
6   2025-04-03   Apples     90
7   2025-04-03  Oranges    110
8   2025-04-03   Apples     85
9   2025-04-04  Oranges    140
10  2025-04-04   Apples    160
11  2025-04-04  Oranges    130
12  2025-04-05   Apples    200
13  2025-04-05  Oranges    210

In [25]:
data = {
    'Date': [
        '2025-04-01', '2025-04-01', '2025-04-01',
        '2025-04-02', '2025-04-02', '2025-04-02',
        '2025-04-03', '2025-04-03', '2025-04-03',
        '2025-04-04', '2025-04-04', '2025-04-04',
        '2025-04-05', '2025-04-05'
    ],
    'Product': [
        'Apples', 'Oranges', 'Apples',
        'Oranges', 'Apples', 'Oranges',
        'Apples', 'Oranges', 'Apples',
        'Oranges', 'Apples', 'Oranges',
        'Apples', 'Oranges'
    ],
    'Sales': [
        100, 150, 130,
        120, 180, 100,
        90, 110, 85,
        140, 160, 130,
        200, 210
    ]
}
df = pd.DataFrame(data)
display(df)

pd.pivot_table(df, values='Sales', index='Date', columns='Product', aggfunc='max')

          Date  Product  Sales
0   2025-04-01   Apples    100
1   2025-04-01  Oranges    150
2   2025-04-01   Apples    130
3   2025-04-02  Oranges    120
4   2025-04-02   Apples    180
5   2025-04-02  Oranges    100
6   2025-04-03   Apples     90
7   2025-04-03  Oranges    110
8   2025-04-03   Apples     85
9   2025-04-04  Oranges    140
10  2025-04-04   Apples    160
11  2025-04-04  Oranges    130
12  2025-04-05   Apples    200
13  2025-04-05  Oranges    210

Product     Apples  Oranges
Date
2025-04-01     130      150
2025-04-02     180      120
2025-04-03      90      110
2025-04-04     160      140
2025-04-05     200      210

In [26]:
df = pd.read_csv('Sales_Funnel_CRM.csv')
df

print(f'calc how many licenses sold for each company from each product -- pivot table?')
# calc how many licenses sold for each company from each product -- pivot table
display(pd.pivot_table(df, values='Licenses', index='Company', columns='Product', aggfunc='sum', fill_value=0))

print(f'calc what is the max Sale-Price for each srarys fo each company?')
# calc what is the max Sale-Price for each Status for each company
display(pd.pivot_table(df, values='Sale Price', index='Company', columns='Product', aggfunc='max', fill_value=0))

calc how many licenses sold for each company from each product -- pivot table?

Product       Analytics  GPS Positioning  Prediction  Tracking
Company
 Google             150                0         150       300
ATT                   0                0         150       150
Apple               300                0           0         0
BOBO                150                0           0         0
CVS Health            0                0           0       450
Cisco               300              300           0         0
Exxon Mobile        150                0           0         0
IKEA                300                0           0         0
Microsoft             0                0           0       300
Salesforce          750                0           0         0
Tesla Inc.          300                0         150         0
Walmart             150                0           0         0

calc what is the max Sale-Price for each srarys fo each company?

Product       Analytics  GPS Positioning  Prediction  Tracking
Company
 Google         2100000                0      700000    350000
ATT                   0                0      700000    350000
Apple           4550000                0           0         0
BOBO            2450000                0           0         0
CVS Health            0                0           0    490000
Cisco           4550000           350000           0         0
Exxon Mobile    2100000                0           0         0
IKEA            4550000                0           0         0
Microsoft             0                0           0    350000
Salesforce      7000000                0           0         0
Tesla Inc.      2800000                0      700000         0
Walmart         2450000                0           0         0