In [1]:
import pandas as pd
import numpy  as np
from IPython.display import display

In [2]:
df = pd.read_csv('tips2.csv')
display(df)

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251
...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672

In [3]:
# Task 1
# Load tips.csv. Display the first rows, df.info(), and df.describe().T. 
#Then add a new column price_per_person calculated as total_bill / size.

display(df.info())
print()
display(df.describe().T)
print()
df['price_per_person '] = df['total_bill'] / df['size']
display(df)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   total_bill        244 non-null    float64
 1   tip               244 non-null    float64
 2   sex               244 non-null    object
 3   smoker            244 non-null    object
 4   day               244 non-null    object
 5   time              244 non-null    object
 6   size              244 non-null    int64
 7   price_per_person  244 non-null    float64
 8   Payer Name        244 non-null    object
 9   CC Number         244 non-null    int64
 10  Payment ID        244 non-null    object
dtypes: float64(3), int64(2), object(6)
memory usage: 21.1+ KB

None

,count,mean,std,min,25%,50%,75%,max
total_bill,244.0,1.978594e+01,8.902412e+00,3.070000e+00,1.334750e+01,1.779500e+01,2.412750e+01,5.081000e+01
tip,244.0,2.998279e+00,1.383638e+00,1.000000e+00,2.000000e+00,2.900000e+00,3.562500e+00,1.000000e+01
size,244.0,2.569672e+00,9.510998e-01,1.000000e+00,2.000000e+00,2.000000e+00,3.000000e+00,6.000000e+00
price_per_person,244.0,7.888197e+00,2.914234e+00,2.880000e+00,5.800000e+00,7.255000e+00,9.390000e+00,2.027000e+01
CC Number,244.0,2.563496e+15,2.369340e+15,6.040679e+10,3.040731e+13,3.525318e+15,4.553675e+15,6.596454e+15

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,price_per_person
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959,8.495000
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608,3.446667
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458,7.003333
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260,11.840000
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251,6.147500
...,...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657,9.676667
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766,13.590000
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880,11.335000
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17,8.910000
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672,9.390000

In [4]:
# Task 2
# Count how many orders (rows) were placed at each time and for each gender.
df[['time', 'sex']].value_counts().sort_index().to_frame()

               count
time   sex
Dinner Female     52
       Male      124
Lunch  Female     35
       Male       33

In [5]:
# Task 3
# Count how many orders (rows) were placed on each day.
df['day'].value_counts().sort_index().to_frame()

      count
day
Fri      19
Sat      87
Sun      76
Thur     62

In [6]:
# Task 4
# Find the maximum price_per_person for each day and gender combination.
maximum_price = df.groupby(['day', 'sex']).mean(numeric_only=True)
display(maximum_price['price_per_person'].to_frame())
display(f'the maximum_price is -> {maximum_price['price_per_person'].max()}')

             price_per_person
day  sex
Fri  Female          6.778889
     Male            9.352000
Sat  Female          8.723214
     Male            7.932203
Sun  Female          6.774444
     Male            8.201724
Thur Female          6.943750
     Male            7.936667

'the maximum_price is -> 9.352'

In [7]:
# Task 5
# Find the minimum price_per_person for each day and size combination.
minimum_price = df.groupby(['day', 'size']).mean(numeric_only=True)
display(minimum_price['price_per_person'].to_frame())
display(f'the minimum_price is -> {minimum_price['price_per_person'].min()}')

           price_per_person
day  size
Fri  1             8.580000
     2             8.161250
     3             5.330000
     4            10.040000
Sat  1             5.160000
     2             8.418113
     3             8.502778
     4             7.468462
     5             5.630000
Sun  2             8.779231
     3             7.394667
     4             6.672222
     5             5.400000
     6             8.030000
Thur 1            10.070000
     2             7.579167
     3             6.387500
     4             7.488000
     5             8.240000
     6             5.066667

'the minimum_price is -> 5.066666666666666'

In [8]:
# Task 6
# Calculate the sum of total_bill grouped by size and smoker status.
# Then use .loc to extract the sum for size 2 smokers only.
Calculate = df.groupby(['size', 'smoker']).mean(numeric_only=True)
print(f'\n The sum of total_bill is -> {Calculate['total_bill'].sum()}\n')
display(Calculate['total_bill'].to_frame())
display(Calculate['total_bill'].loc[[(2,'Yes')]].to_frame())

 The sum of total_bill is -> 250.07436130536126

             total_bill
size smoker
1    No        8.660000
     Yes       5.825000
2    No       15.342333
     Yes      17.955758
3    No       21.009615
     Yes      28.191667
4    No       27.769231
     Yes      30.609091
5    No       30.576667
     Yes      29.305000
6    No       34.830000

             total_bill
size smoker
2    Yes      17.955758

In [9]:
# Task 7
# Display the maximum price_per_person grouped by day and gender. 
# Then use .loc to show the results for Male only across all days.
maximum_price = df.groupby(['day', 'sex']).mean(numeric_only=True)
display(maximum_price['price_per_person'].to_frame())
print(f'\n the maximum price_per_person -> {maximum_price['price_per_person'].max()}\n')
display(maximum_price['price_per_person'].loc[:, 'Male'].to_frame())

             price_per_person
day  sex
Fri  Female          6.778889
     Male            9.352000
Sat  Female          8.723214
     Male            7.932203
Sun  Female          6.774444
     Male            8.201724
Thur Female          6.943750
     Male            7.936667

 the maximum price_per_person -> 9.352

      price_per_person
day
Fri           9.352000
Sat           7.932203
Sun           8.201724
Thur          7.936667